### ISSUE TITLE
Quartz Rescheduler

### ISSUE THREAD

**Issue by AdrianFall** [AdrianFall/Handball-FYP#4]
Probably a problem when rescheduling the job, where group id keeps being appended each consecutive reschedule instead of being overwriten.
Exception:
Re-Scheduling error, for job (schedule:league:781.job:4068:4065) at time: Tue Mar 31 17:18:03 BST 2015. SchedulerException Couldn't store trigger 'group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.RECOVERING_JOBS.recover_NON_CLUSTERED_1427817303767' for 'schedule:league:781.job:4068:4065' job:ERROR: value too long for type character varying(200)
org.quartz.JobPersistenceException: Couldn't store trigger 'group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.group1.RECOVERING_JOBS.recover_NON_CLUSTERED_1427817303767' for 'schedule:league:781.job:4068:4065' job:ERROR: value too long for type character varying(200) [See nested exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(200)]
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1223)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.replaceTrigger(JobStoreSupport.java:1498)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport$11.execute(JobStoreSupport.java:1473)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3787)
    at org.quartz.impl.jdbcjobstore.JobStoreTX.executeInLock(JobStoreTX.java:93)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.replaceTrigger(JobStoreSupport.java:1469)
    at org.quartz.core.QuartzScheduler.rescheduleJob(QuartzScheduler.java:1146)
    at org.quartz.impl.StdScheduler.rescheduleJob(StdScheduler.java:321)
    at af.handball.scheduler.job.MatchJob.rescheduleJob(MatchJob.java:120)
    at af.handball.scheduler.job.MatchJob.execute(MatchJob.java:96)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(200)
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:559)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:363)
    at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
    at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.insertTrigger(StdJDBCDelegate.java:1093)
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.storeTrigger(JobStoreSupport.java:1220)
    ... 11 more

**Comment by AdrianFall** [comment]
possibly fixed in commit #49 https://github.com/AdrianFall/Handball-FYP/commit/b436f71b5428b328689816080cb4bebdf753629b
